### PR TITLE
updates chatbot.js

### PR DESCRIPTION
**Pull request by Yash17Agrawal**
Updated chatbot.js for morejokes api

### CODE REVIEW

**Comment by yashmehrotra** [comment]
Please add this in the #10 PR

**Comment by Yash17Agrawal** [comment]
I dont know how to merge two PRs but will do it tomorrow definitely.

**Comment by 526avijitgupta** [comment]
@Yash17Agrawal The best way to proceed further would be to close this PR and instead cherry-pick this commit to the branch `Yash17Agrawal-patch-1` so that this is reflected in your 1st PR only!

**Comment by yashmehrotra** [comment]
@526avijitgupta Cherrypicking won't work, this commit is not upto date with master, moreover, with the changes that I suggested in #10, changes in chatbot won't be necessary.

**Pull request closed without merging**
