### PR TITLE
Local testing functionality

### PR DESCRIPTION
**Pull request by yashmehrotra**

### CODE REVIEW

**Comment by yashmehrotra** [comment]
@526avijitgupta Please es6 it and merge it

**Comment by 526avijitgupta** [comment]
@yashmehrotra Will do in a few days.

**Comment by 526avijitgupta** [comment]
@yashmehrotra Please review.

**Comment by yashmehrotra** [comment]
@526avijitgupta LGTM. Have you tested it locally well, if yes, merge it.

**Pull request merged**
