### PR TITLE
Fix #1: Add more joke APIs

### LINKED ISSUE #1: Integrate more Open Joke APIs
Currently, jokes are only fetched through [Internet Chuck Norris Database](http://api.icndb.com/jokes/random).

It would be nice if we integrate more joke platforms in this.

### PR DESCRIPTION
**Pull request by Yash17Agrawal**
It will solve the problem of having the same pattern of jokes of chuck norris .

### CODE REVIEW

**Comment by yashmehrotra** [comment]
@Yash17Agrawal Instead of this, make a list of urls and add this and chuck norris one to it, with a function calling either 2 of the previous api's randomly

**Comment by yashmehrotra** [comment]
@Yash17Agrawal Since, this PR is related to #1 , also add an API which sends programming jokes

**Comment by 526avijitgupta** [comment]
@Yash17Agrawal Any updates on this ?

**Comment by Yash17Agrawal** [comment]
@526avijitgupta  sir i have done it ,but wanted to meet you before any further pull request.So when will you be back in hostel?

**Comment by 526avijitgupta** [comment]
@Yash17Agrawal Please try and wrap this up!

**Comment by Yash17Agrawal** [comment]
@526avijitgupta  Sure sir !

**Comment by 526avijitgupta** [comment]
Closing in favor of #22

**Pull request closed without merging**
